### ISSUE TITLE
Improve snippets behavior

### ISSUE THREAD

**Issue by Adam-it** [garrytrinder/dev-proxy-toolkit#23]
some snippets could provide even more help and handy behavior for the user.

for example the snippet `devproxy-plugin-crud-api-action` creates the following part of json
```
   {
        "action": "",
        "method": "",
        "query": "",
        "url": ""
    }
```

but in a way the user works doesn't stop there. the user will need to still go over each property and fill it. 
I was thinking we could improve that adding tabstops/placeholders to some snippets (like this one).  You may do that by adding the `$1` `$2` etc to your snippet definition. 
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_tabstops

as an example the CLI for Microsoft 365 VS Code extension uses tab stops in every snippets that have some required option that needs to be set. That way after the snippet code is added the user may use tab to move between next options. Like this

https://github.com/garrytrinder/dev-proxy-toolkit/assets/58668583/4c654cc5-3245-4461-b2f7-78cb1826e1d3

**Comment by Adam-it** [comment]
> Great suggestion @Adam-it I'm sure there will be more updates we can do across the board to tweak the snippets to improve the experience.
> 
> For the snippet you've highlighted, this does have placeholders already.
> 
> https://github.com/garrytrinder/dev-proxy-toolkit/blob/011906c212902df868db3084a826dc922a64bdfb/src/snippets.json#L143-L155
> 
> I have however found that if you have Copilot enabled, this can cause issues with the tab behaviour.

True as copilot gives a suggestion and tab approves it. This may be problematic indeed 👍

**Comment by garrytrinder** [comment]
I'll close this issue for now as we do implement placeholders across the snippets where they are appropriate.

Thanks again for the suggestion.
