### ISSUE TITLE
I seems I am unable to run diagnostics check for plugin array

### ISSUE THREAD

**Issue by Adam-it** [garrytrinder/dev-proxy-toolkit#24]
The JSON validation works really nice and as you may see it validates the empty URL.

![image](https://github.com/garrytrinder/dev-proxy-toolkit/assets/58668583/e17465c1-c89c-419a-8bff-98e6df3a8ec6)

but for some reason it does not validate the empty plugin array 🤔. Not sure what am I doing wrong.

**Comment by garrytrinder** [comment]
This isn't something that is actually implemented, you can run proxy without a plugin, but you must have a URL to watch.

This is something that we can implement as a visual cue however, using a warning rather than an error would be more appropriate I think.

**Comment by garrytrinder** [comment]
Thanks @Adam-it I've raised an issue to add the warning 👍
